### ISSUE TITLE
ImportError: No module named directory

### ISSUE THREAD

**Issue by jpswade** [tkem/mopidy-podcast-gpodder#4]
```
ERROR    Extension podcast-gpodder failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_podcast_gpodder/__init__.py", line 34, in setup
    from .directory import GPodderDirectory
  File "/usr/local/lib/python2.7/dist-packages/mopidy_podcast_gpodder/directory.py", line 9, in <module>
    from mopidy_podcast.directory import PodcastDirectory
ImportError: No module named directory
```

**Comment by tkem** [comment]
Thanks for reporting. I've completely forgotten about this...

I'm sorry to let you know that gpodder.net support will be deprecated. There hasn't been that much interest in this, and I don't actively use it myself any more, so it won't get updated (at least by me) to be compatible with Mopidy-Podcast v2.0.
